# Site settings
name: Marcus Tan
title: Marcus Tan | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://marcustan-dev.github.io/
baseurl: ''
email: marcus@mtss.dev
cover: https://marcustan-dev.github.io/img/og.png
logo: https://marcustan-dev.github.io/img/emojis/technologist.png
resume: https://marcustan-dev.github.io/resume.pdf
social:
  - title: email
    url: mailto:marcus@mtss.dev
  - title: twitter
    url: https://twitter.com/bchiang7
  - title: instagram
    url: https://instagram.com/bchiang7
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/bchiang7
  - title: linkedin
    url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
